---
name: Energy Benchmark Cloudflare Worker
author: Arne Tarara <arne@green-coding.io>
description: Run wrangler on brach magazine page dump and benchmark energy and carbon

services:
  node:
    image: node:25.1.0-bookworm-slim
    setup-commands:
      - command: apt update
      - command: apt install git curl -y
      - command: cp -R /tmp/repo/cloudflare-worker /cloudflare-worker
      - command: echo '__GMT_VAR_EMAPS_KEY__' > /cloudflare-worker/.dev.vars
        shell: bash
      - command: cd /cloudflare-worker && npm install
        shell: bash
      - command: cd /cloudflare-worker && npx http-server --port 8080
        shell: bash
        detach: true
      - command: cd /cloudflare-worker && npx wrangler dev --ip 127.0.0.1 | tee /tmp/wrangler.log
        shell: bash
        detach: true

flow:
  - name: Visit page to trigger cloudflare worker transform
    container: node
    commands:
      - type: console
        command: curl http://localhost:8787/ --connect-timeout 5 -o /dev/null

  - name: Validate Rewrite
    container: node
    hidden: true
    commands:
      - type: console
        command: grep "LOW REWRITE DONE" /tmp/wrangler.log


